export const IPC = {
  dbListSessions: 'db:listSessions',
  dbCreateSession: 'db:createSession',
  dbStartSession: 'db:startSession',
  dbEndSession: 'db:endSession',
  dbListGoals: 'db:listGoals',
  dbCreateGoal: 'db:createGoal',
  dbListContentItems: 'db:listContentItems',
  dbCreateContentItem: 'db:createContentItem',
  dbUpdateContentItemStatus: 'db:updateContentItemStatus',
  dbListActivity: 'db:listActivity',
  dbListChecklistItems: 'db:listChecklistItems',
  dbCreateChecklistItem: 'db:createChecklistItem',
  dbDeleteChecklistItem: 'db:deleteChecklistItem',
  dbCreateMetricSnapshot: 'db:createMetricSnapshot',
  dbListMetricSnapshotsForSession: 'db:listMetricSnapshotsForSession',
  dbListMetricSnapshots: 'db:listMetricSnapshots',
  dbListAutomationRuns: 'db:listAutomationRuns',
  automationRunContentReviewCheck: 'automation:runContentReviewCheck',
  obsGetStatus: 'obs:getStatus',
  obsStatusChanged: 'obs:status-changed',
  obsGetSettings: 'obs:getSettings',
  obsSaveSettings: 'obs:saveSettings',
  obsStartStream: 'obs:startStream',
  obsStopStream: 'obs:stopStream'
} as const
